### ISSUE TITLE
Do we need attrs as streams? Can we just rely on nullish values instead?

### ISSUE THREAD

**Issue by pygy** [vellajs/vella#21]
In order to settle #16, it would be nice to discuss the semantics of setting and removing attributes, properties and events. Here's a brain dump of what I think so far:

Setting aside SVG (whose props are mostly readonly):

With the DOM:
- Attributes and events can be set, updated and removed
- IDL properties can only be set or updated. `deleting` a property is a noop, because the getters/setters are defined on the prototypes.

With vella:

- `()=> c() ? {foo} : {}`, going from `c() === true` to `c() === false`:
  - when it is detected as an event, the event is removed
  - when `foo` is detected as a property, it is set to `null` (and ~automatically turned into a `"null"` string by the browser). There are a few exceptions for problematic setters, that fall back on setting the attributes.
  - otherwise it is treated as an attribute, which is removed.

... and as it ought to work once #11 and #13 are addressed

- `{foo: ()=> (c() ? foo : null)}`
Basically does the same.

The trouble with the scheme above is that most relevant attributes have equally named IDL properties that take precedence. So you can't remove most attributes right now, they end up being set to `"null"`. For most values setting them to `""`  would be better, (that's what most getters return when the attribute is not set, and it is cast to false for boolean attrs such as `checked` or `selected`)... but not perfect. As far as CSS and `querySelectorAll` go , `<b id="">` and `<b>` are distinct. Also, setting `input.checked = true` does not set the corresponding attribute, so you can use `input[type='checkbox'][checked]` to style it, but you can use `input[type='checkbox']:checked` (which I suppose is a best practice in a post IE8 world).

From a purely semantic point of view, for HTML elements, it would be better to be able to set and remove the attributes (I think it would require a ), but I don't know if that matters in practice, since there are workaround in userland for most problems.

We can't also not just set the attributes, the `property in element` check is important for custom element to work properly.

So the only advantage of streams as attrs I see right now is that it lets one set/remove/update several values in one fell swoop. I think that's nice to have semantically, but it hampers writing clean hyperscript...

Stream as attrs have the disadvantage that they let one accidentally remove a property, which is nonsensical.

My knowledge of HTML, IDL and CSS is incomplete though so I'd like to be sure I'm not missing something crucial.

**Comment by CreaturesInUnitards** [comment]
I don't believe the benefits of `attrs` as streams outweigh the ergonomic benefits of optional `attrs`.

I think if attribute removal proves to be a serious issue, we really should consider a sentinel specifically for that purpose. We can still allow `null` children, but passing e.g. `v.null` to remove an attribute seems to me to be the simplest and most likely the most performant.

**Comment by pygy** [comment]
Oooh, I'm an idiot...

Without attrs as streams how do we remove event listeners? You can't pass a stream/live zone as an event listener like you can for other values...

I knew this, but let it slip somehow.
